import { createClient } from "@/lib/supabase/server";
import type { ServiceReport } from "./types";

/**
 * ------------------------------------------------------------------
 * SUPABASE-BACKED STORE
 * ------------------------------------------------------------------
 * Same function signatures as the local JSON version, so nothing in
 * your pages/components needs to change — only this file did.
 * job_no is assigned automatically by the database (see
 * service_report_schema.sql — generate_job_no()), so we never set it
 * from application code.
 * ------------------------------------------------------------------
 */

// Maps a Postgres row (snake_case) to the app's ServiceReport type (camelCase)
function mapRow(row: any, parts: any[] = []): ServiceReport {
  return {
    id: row.id,
    jobNo: row.job_no,
    refNo: row.ref_no ?? "",
    date: row.report_date,
    clientName: row.client_name ?? "",
    userName: row.user_name ?? "",
    contactNo: row.contact_no ?? "",
    equipment: row.equipment ?? "",
    brand: row.brand ?? "",
    model: row.model ?? "",
    snCrNo: row.sn_cr_no ?? "",
    typeOfService: row.type_of_service ?? [],
    othersText: row.others_text ?? "",
    jobScope: row.job_scope ?? "",
    actionTaken: row.action_taken ?? "",
    conclusion: row.conclusion ?? "",
    parts: parts.map((p) => ({
      id: p.id,
      description: p.description,
      qty: p.qty,
    })),
    customerName: row.customer_name ?? "",
    customerDate: row.customer_signed_at ?? "",
    customerSignature: row.customer_signature_url ?? null,
    technicianName: row.technician_name ?? "",
    technicianDate: row.technician_signed_at ?? "",
    technicianSignature: row.technician_signature_url ?? null,
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export async function listReports(): Promise<ServiceReport[]> {
  const supabase = await createClient();
  const { data: reports, error } = await supabase
    .from("service_reports")
    .select("*, parts_replaced(*)")
    .order("created_at", { ascending: false });

  if (error) throw error;
  return (reports ?? []).map((r: any) => mapRow(r, r.parts_replaced));
}

export async function getReport(id: string): Promise<ServiceReport | undefined> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("service_reports")
    .select("*, parts_replaced(*)")
    .eq("id", id)
    .single();

  if (error) return undefined;
  return mapRow(data, data.parts_replaced);
}

export async function createReport(): Promise<ServiceReport> {
  const supabase = await createClient();
  // job_no is auto-generated by the database default — no need to pass it.
  const { data, error } = await supabase
    .from("service_reports")
    .insert({})
    .select()
    .single();

  if (error) throw error;
  return mapRow(data, []);
}

export async function updateReport(
  id: string,
  updates: Partial<ServiceReport>
): Promise<ServiceReport | undefined> {
  const supabase = await createClient();

  const { parts, ...rest } = updates;

  const dbUpdates: Record<string, any> = {
    ref_no: rest.refNo,
    report_date: rest.date,
    client_name: rest.clientName,
    user_name: rest.userName,
    contact_no: rest.contactNo,
    equipment: rest.equipment,
    brand: rest.brand,
    model: rest.model,
    sn_cr_no: rest.snCrNo,
    type_of_service: rest.typeOfService,
    others_text: rest.othersText,
    job_scope: rest.jobScope,
    action_taken: rest.actionTaken,
    conclusion: rest.conclusion,
    customer_name: rest.customerName,
    customer_signed_at: rest.customerDate || null,
    customer_signature_url: rest.customerSignature,
    technician_name: rest.technicianName,
    technician_signed_at: rest.technicianDate || null,
    technician_signature_url: rest.technicianSignature,
    status: rest.status,
  };
  // Drop undefined keys so we don't overwrite existing values with null.
  Object.keys(dbUpdates).forEach(
    (k) => dbUpdates[k] === undefined && delete dbUpdates[k]
  );

  const { data, error } = await supabase
    .from("service_reports")
    .update(dbUpdates)
    .eq("id", id)
    .select()
    .single();

  if (error) throw error;

  if (parts) {
    // Replace all parts rows for this report (simplest correct approach
    // for a small repeating table like this).
    await supabase.from("parts_replaced").delete().eq("service_report_id", id);
    if (parts.length > 0) {
      await supabase.from("parts_replaced").insert(
        parts.map((p) => ({
          service_report_id: id,
          description: p.description,
          qty: p.qty,
        }))
      );
    }
  }

  return getReport(id);
}

export async function deleteReport(id: string): Promise<boolean> {
  const supabase = await createClient();
  const { error } = await supabase.from("service_reports").delete().eq("id", id);
  return !error;
}
